### ISSUE TITLE
Automate this stuff.

### ISSUE THREAD

**Issue by ElanHasson** [InfinityFlowApp/CRDs-catalog#14]
I would like to propose automating this repository:

1. Create an index of URLs of CRDs
2. Periodically spider them (perhaps watch releases of GitHub projects with CRDs) using GHA cron jobs
3. Auto create PRs here of there are changes

Thoughts?

**Comment by ElanHasson** [comment]
CC @NicholasRaymondiSpot @snovak7

**Comment by NicholasRaymondiSpot** [comment]
Agreed, it would be nice to have a validation check hooked up to it. I could probably provide a sample manifest for the three CRDs (EC2NodeClass, NodeClaim & NodePool) using the examples Karpenter provides, then part of the job could be to use it for compiling & validation. We use this and diff the output as part of our workflow, then put an approval gate in place so we can review the changes and merge them in if they're valid/wanted.
